# netlify.toml
[[redirects]]
  from     = "/*"
  to       = "https://www.yummypooch.com/:splat"
  status   = 200      # "proxy" mode
  force    = true     # override everything

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options         = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *;"
