[build]
  # point Netlify at your Functions folder
  functions = "netlify/functions"

[[redirects]]
  # catch all requests and send them to our proxy function
  from     = "/*"
  to       = "/.netlify/functions/proxy/:splat"
  status   = 200    # proxy mode
  force    = true
