# [build]
#   functions = "netlify/functions"

# [[redirects]]
#   from     = "/*"
#   to       = "/.netlify/functions/proxy/:splat"
#   status   = 200    # proxy mode
#   force    = true
[build]
  # Tell Netlify where to find Edge Functions
  edge_functions = "netlify/edge-functions"
