# netlify.toml
[[redirects]]
  from     = "/*"
  to       = "https://www.yummypooch.com/:splat"
  status   = 200
  force    = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options           = "ALLOWALL"
    Content-Security-Policy   = "frame-ancestors *;"
