# netlify.toml

[[redirects]]
  from     = "/*"
  to       = "https://www.yummypooch.com/:splat"
  status   = 200      # <-- proxy mode
  force    = true     # <-- override everything

[[headers]]
  for = "/*"
  [headers.values]
    # Allow our Netlify site to be iframed anywhere (including Adalo)
    Content-Security-Policy = "frame-ancestors *;"
    # Remove Shopify’s X-Frame-Options
    X-Frame-Options         = ""
