[build]
  # Point to the Functions folder
  functions = "netlify/functions"

# Redirect all paths into our proxy function
[[redirects]]
  from     = "/*"
  to       = "/.netlify/functions/proxy/:splat"
  status   = 200    # proxy mode
  force    = true
